-- Insert para contenido_genero
INSERT INTO contenido_genero (contenido_id, genero_id) VALUES
(1, 1),  
(1, 2),  
(2, 1),  
(2, 3),  
(3, 2),   
(3, 4);  

-- Insert para genero
INSERT INTO genero (genre_name) VALUES
('Sci-Fi'),
('Fantasía'),
('Acción'),
('Drama'),
('Ficción'),
('Sucesos'),
('Misterio'),
('Crimen'),
('Suspenso'),
('Aventura'),
('Comedia'),
('Familia'),
('Western'),
('Terror'),
('Tecnología'),
('Romance'),
('Música'),
('Animación'),
('Ciencia ficción');

-- Insert para la tabla actor 
INSERT INTO actor (first_name, last_name) VALUES 
('Tom', 'Hanks'),
('Meryl', 'Streep'),
('Brad', 'Pitt'),
('Natalie', 'Portman'),
('Robert', 'De Niro'),
('Al', 'Pacino'),
('Leonardo', 'DiCaprio'),
('Scarlett', 'Johansson'),
('Denzel', 'Washington'),
('Julia', 'Roberts'),
('Jennifer', 'Lawrence'),
('Hugh', 'Jackman'),
('Emma', 'Stone'),
('Angelina', 'Jolie'),
('Ryan', 'Gosling'),
('Matthew', 'McConaughey'),
('Chris', 'Evans'),
('Johnny', 'Depp'),
('Kate', 'Winslet'),
('Harrison', 'Ford'),
('Anne', 'Hathaway'),
('Ben', 'Affleck'),
('Chris', 'Pratt'),
('Jason', 'Statham'),
('Gal', 'Gadot'),
('Tom', 'Hardy'),
('Vin', 'Diesel'),
('John', 'C. Reilly'),
('Joaquin', 'Phoenix'),
('Idris', 'Elba'),
('Michelle', 'Williams'),
('Daniel', 'Craig'),
('Renee', 'Zellweger'),
('Sofia', 'Vergara'),
('Kristen', 'Bell'),
('Ben', 'Stiller'),
('Michael', 'B. Jordan'),
('Chris', 'Hemsworth'),
('Samuel', 'L. Jackson'),
('Paul', 'Rudd'),
('John', 'Goodman'),
('Will', 'Smith'),
('Zoe', 'Saldana'),
('Jessica', 'Chastain'),
('Viola', 'Davis'),
('Charlize', 'Theron'),
('Seth', 'Rogen'),
('Jonah', 'Hill'),
('Kristen', 'Wiig'),
('Alicia', 'Vikander'),
('Rami', 'Malek'),
('Octavia', 'Spencer'),
('Awkwafina', ''),
('Maya', 'Rudolph'),
('Melissa', 'McCarthy'),
('Bette', 'Midler'),
('John', 'Lithgow'),
('Jeff', 'Bridges'),
('Taraji', 'P. Henson'),
('Chris', 'Pine'),
('John', 'David Washington'),
('Robert', 'Pattinson'),
('Kristen', 'Stewart'),
('Tessa', 'Thompson'),
('Chris', 'O\'Dowd'),
('Mena', 'Massoud'),
('Naomi', 'Scott'),
('Ken', 'Jeong'),
('Angela', 'Bassett'),
('Will', 'Poulter'),
('Letitia', 'Wright'),
('Josh', 'Brolin'),
('John', 'Boyega'),
('Nathalie', 'Emmanuel'),
('Maria', 'Bakalova'),
('Kevin', 'Hart'),
('Eric', 'Andre'),
('Timothée', 'Chalamet'),
('Emilia', 'Clarke'),
('Maisie', 'Williams'),
('Sophie', 'Turner'),
('Matt', 'Bomer'),
('Iwan', 'Rheon'),
('Joe', 'Keery'),
('Sadie', 'Sink'),
('Natalia', 'Dyer'),
('Charlie', 'Heaton'),
('Winona', 'Ryder'),
('David', 'Harbour'),
('Finn', 'Wolfhard'),
('Gaten', 'Matarazzo'),
('Caleb', 'McLaughlin'),
('Maya', 'Hawke'),
('Uma', 'Thurman'),
('Margot', 'Robbie'),
('Anthony', 'Mackie'),
('Brie', 'Larson'),
('Dwayne', 'Johnson'),
('Jason', 'Momoa'),
('Mark', 'Ruffalo'),
('Jeremy', 'Renner'),
('Robert', 'Downey Jr.'),
('Chadwick', 'Boseman'),
('Danai', 'Gurira'),
('Lupita', 'Nyong\'o'),
('Ryan', 'Coogler'),
('Jared', 'Leto'),
('Aidan', 'Gallagher'),
('Elle', 'Fanning'),
('Reba', 'McEntire'),
('Bob', 'Odenkirk'),
('David', 'Cross'),
('Parker', 'Posey'),
('Elizabeth', 'Banks'),
('Amy', 'Adams'),
('Nicole', 'Kidman'),
('John', 'C. Reilly'),
('Jason', 'Bateman'),
('Judy', 'Greer'),
('Tiffany', 'Haddish'),
('Kumail', 'Nanjiani'),
('Aidy', 'Bryant'),
('Kate', 'McKinnon'),
('Cecily', 'Strong'),
('Pete', 'Davidson'),
('Bowen', 'Yang'),
('Colin', 'Jost'),
('Michael', 'Che'),
('Kenan', 'Thompson'),
('Leslie', 'Jones'),
('Fred', 'Armisen'),
('Andy', 'Samberg'),
('Bill', 'Hader'),
('Tina', 'Fey'),
('Amy', 'Poehler'),
('Rachel', 'Dratch'),
('Vanessa', 'Bayer'),
('Heidi', 'Gardner'),
('Chloe', 'Fineman'),
('Punkie', 'Johnson'),
('Lauren', 'Holt'),
('Nasim', 'Pedrad'),
('Nasim', 'Pedrad'),
('Ego', 'Nwodim'),
('Kyle', 'Mooney'),
('Beck', 'Bennett'),
('Andrew', 'Dismukes'),
('Mikey', 'Day'),
('Alex', 'Moffat'),
('Ego', 'Nwodim'),
('Chloe', 'Fineman'),
('Heidi', 'Gardner');
